export const ADD_EMPLOYEES='ADD_EMPLOYEES'
export const DELETE_EMPLOYEES='DELETE_EMPLOYEES'

export const LOAD_EMPLOYEES_REQUEST='LOAD_EMPLOYEES_REQUEST'
export const LOAD_EMPLOYEES_SUCCESS='LOAD_EMPLOYEES_SUCCESS'
export const LOAD_EMPLOYEES_FAILURE='LOAD_EMPLOYEES_FAILURE'

